config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  resources :users, only: [:show, :edit, :update]
  get 'users/:id/leave' => 'users#leave', as: 'users_leave'

  resources :posts do
    # いいね
    resources :likes, only: [:create, :destroy]

    # コメント
    resources :comments, only: [:create, :destroy]
  end

  # アバウト画面
  get 'home/about' => 'homes#about'

  # トップ画面
  get 'home/top' => 'homes#top'

  # 通知機能
  resources :notifications, only: :index
  resources :notifications do
    collection do
      delete 'destroy_all'
    end
  end

  # お問い合わせ画面
  get 'contacts/new'
  post 'contacts/create'

  # 検索画面
  get  'search' => 'searches#search', as: 'search'

  # トップ画面
  get '/' => 'homes#top', as: 'root'

  # admin側トップ画面
  namespace :admins do
    get 'homes/top'
  end

  # admin側/ユーザー関連
  namespace :admins do
    resources :users
  end

  # admin側/投稿関連
  namespace :admins do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
	# スコープ（新着順）
	default_scope->{order(created_at: :desc)}

	# アソシエーション
	belongs_to :post, optional: true
	belongs_to :comment, optional: true
	belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
	belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	def index
		@notifications = current_user.passive_notifications
		@notifications.where(checked: false).each do |notification|
			notification.update_attributes(checked: true)
		end
	end

	def destroy_all
		@notifications = current_user.passive_notifications.destroy_all
		redirect_to notifications_path
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
	def notification_form(notification)
		@visiter = notification.visiter
		@comment = nil
		your_post = link_to 'あなたの投稿', post_path(notification), style:"font-weight: bold;"
		@visiter_comment = notification.comment_id
		case notification.action
		when "like" then
			tag.a(notification.visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:post_path(notification.post_id), style:"font-weight: bold;")+"にいいねしました"
		when "comment" then
			@comment = Comment.find_by(id: @visiter_comment)
			tag.a(@visiter.name, href:user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:post_path(notification.post_id), style:"font-weight: bold;")+"にコメントしました"
		end
	end

	def unchecked_notifications
	    @notifications = current_user.passive_notifications.where(checked: false)
	end

end

app/views/notifications/_nitification.html.erb
<% visiter = notification.visiter %>
<% item = notification.item %>

<div class="user-view clearfix ">
  <%= link_to users_user_path(notification.visiter) do %>
    <%= attachment_image_tag visiter, :profile_image, :fill,100,100, format: "jpeg", fallback: "no_image.jpg", size: "50x50", class:"profile-img-circle" %>
  <% end %>
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)} 前)" %></span>
  <br>
  <% if !@comment.nil? %>
    <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @comment %></p>
  <% end %>
</div>

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% post = notification.post %>

<div class="user-view clearfix ">
  <%= link_to user_path(notification.visiter) do %>
    <%= attachment_image_tag visiter, :profile_image, :fill,100,100, format: "jpeg", fallback: "profile1.jpg", size: "100x100", class:"notification_icon" %>
  <% end %>
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)} 前)" %></span>
  <br>
</div>

app/views/notifications/index.html.erb
<div class="container">
	<div class="row">
		<h4 class="text-center">通知</h4>
		<%= link_to destroy_all_notifications_path, method: :delete do %>
			<i class="fas fa-trash" style="color: black;"></i>
	        <h7 style="color: black;">全削除</h7>
	    <% end %>
	    <% if @notifications.exists? %>
    <div class="users-index">
        <%= render @notifications %>
    </div>
<% else %>
    <p>通知はありません</p>
<% end %>
	</div>
</div>