config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  resources :users, only: [:show, :edit, :update]
  get 'users/:id/leave' => 'users#leave', as: 'users_leave'

  resources :posts do
    # いいね
    resources :likes, only: [:create, :destroy]

    # コメント
    resources :comments, only: [:create, :destroy]
  end

  # アバウト画面
  get 'home/about' => 'homes#about'

  # トップ画面
  get 'home/top' => 'homes#top'

  # 通知機能
  resources :notifications, only: :index
  resources :notifications do
    collection do
      delete 'destroy_all'
    end
  end

  # お問い合わせ画面
  get 'contacts/new'
  post 'contacts/create'

  # 検索画面
  get  'search' => 'searches#search', as: 'search'

  # トップ画面
  get '/' => 'homes#top', as: 'root'

  # admin側トップ画面
  namespace :admins do
    get 'homes/top'
  end

  # admin側/ユーザー関連
  namespace :admins do
    resources :users
  end

  # admin側/投稿関連
  namespace :admins do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    # アソシエーション
    has_many :posts, dependent: :destroy

    has_many :likes, dependent: :destroy
    has_many :liked_posts, through: :likes, source: :post

    # Notificationモデルのforeign_key: "visiter_id" で、visiter_idを参考に、active_notificationsモデルへアクセスする
    has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
    has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

    def already_liked?(post) # 既にいいねしているか？
        likes.exists?(post_id: post.id)
    end

    attachment :profile_image

    # バリデーション
    # パスワードが確認用と一致している事
    validates :encrypted_password, confirmation: true, length: { minimum: 6 }
    # 名前は空白ではいけない
    validates :name, presence: true
    # メールアドレスは空白ではいけない
    validates :email, presence: true
    # メール、存在性、フォーマット、一意性の検証
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
    validates :email, { format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } }

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:member_status] == "false" # 退会用の記述
      @user.user_status = false
      @user.update(user_params)
      reset_session # ログアウトする
      redirect_to root_path
      return # ここから下は実行されない
    else
      if @user.update(user_params) # 会員情報の編集
        redirect_to user_path(@user.id), notice: "変更内容を更新しました"
      else # エラーメッセージ表示用
        render 'edit'
        end
    end
  end

  def leave
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :user_status)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h4>ユーザー情報編集</h4>

			<%= form_for(@user) do |f| %>
				<!-- エラー文表示 -->
				<% if @user.errors.any? %>
					<div id="error_explanation">
						<h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
						<ul>
							<% @user.errors.full_messages.each do |message| %>
								<li><%= message %></li>
							<% end %>
						</ul>
					</div>
				<% end %>

				<div class="row">
					<div class="form-group">
						<p class="col-lg-3">名前</p>
						<div class="col-lg-9" style="padding-bottom: 10px;">
							<%= f.text_field :name, placeholder:"名前" %><br />
						</div>
					</div>
				</div>

				<div class="row">
					<div class="form-group">
						<p class="col-lg-3">メールアドレス</p>
						<div class="col-lg-9" style="padding-bottom: 10px;">
							<%= f.email_field :email %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="form-group">
						<p class="col-lg-3">プロフィール画像</p>
						<div class="col-lg-9" style="padding-bottom: 10px;">
							<%= f.attachment_field :profile_image %>
						</div>
					</div>
				</div>

				<%= f.submit "変更内容を保存する" %>
				<%= link_to "退会する", users_leave_path(current_user.id) %>
			<% end %>

		</div>
		<div class="col-lg-2"></div>
	</div>
</div>

app/views/users/leave.html.erb
<div class="container">
	<div class="col-xs-3"></div>
	<div class="col-xs-12 col-sm-7">

		<h2>本当に退会しますか？</h2>

		<p>退会すると、会員登録情報が閲覧できなくなります。<br>
		退会する場合は、「退会する」をクリックしてください。</p>

		<div style="margin-top: 30px; margin-left: 30px;">
			<div class="row">
				<div class="col-xs-12 col-sm-7">
					<%= form_for(@user, url: user_path) do |f| %>
						<%= f.hidden_field :member_status, :value => false %>
						<%= link_to "退会しない", edit_user_path(current_user.id) %>
						<div style="float: right;">
							<%= f.submit '退会する', data: {"turbolinks" => false}, data: {confirm: "退会しますか？"} %>
						</div>
					<% end %>
				</div>
			</div>
		</div>

	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<% if flash[:notice] %> <!-- サクセスメッセージ -->
			<div class="flash">
				<%= flash[:notice] %>
			</div>
		<% end %>
		<div class="col-sm-4">
			<h4>マイページ</h4>
			<%= link_to "編集する", edit_user_path(@user.id) %>
			<h3>ユーザー詳細</h3>
			<table class="table table-striped">
				<tbody>
					<tr>
						<th>ユーザー名</th>
						<td><%= @user.name %></td>
					</tr>
					<tr>
						<th>メールアドレス</th>
						<td><%= @user.email %></td>
					</tr>
					<tr>
						<th>プロフィール画像</th>
						<td><%= attachment_image_tag @user, :profile_image, :fill, 200, 200, fallback: "profile1.jpg", size: "200x200" %></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="col-sm-7">
			<h4>いいねした投稿</h4>
			<% @user.liked_posts.each do |post| %>
				<div class="showpost">
					<%= link_to post_path(post.id) do %>
						<%= post.title %><br>
						<%= attachment_image_tag post, :post_image, :fill, 200, 200, fallback: "profile1.jpg", size: "200x200" %><br>
					<% end %>
				</div>
			<% end %>
		</div>
	</div>
</div>