config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations',
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
  }

  resources :users, only: [:show, :edit, :update]
  get 'users/:id/leave' => 'users#leave', as: 'users_leave'

  resources :posts do
    # いいね
    resources :likes, only: [:create, :destroy]

    # コメント
    resources :comments, only: [:create, :destroy]
  end

  # アバウト画面
  get 'home/about' => 'homes#about'

  # トップ画面
  get 'home/top' => 'homes#top'

  # 通知機能
  resources :notifications, only: :index
  resources :notifications do
    collection do
      delete 'destroy_all'
    end
  end

  # お問い合わせ画面
  get 'contacts/new'
  post 'contacts/create'

  # 検索画面
  get  'search' => 'searches#search', as: 'search'

  # トップ画面
  get '/' => 'homes#top', as: 'root'

  # admin側トップ画面
  namespace :admins do
    get 'homes/top'
  end

  # admin側/ユーザー関連
  namespace :admins do
    resources :users
  end

  # admin側/投稿関連
  namespace :admins do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parkfun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Vast+Shadow&display=swap" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">メニュー</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if admin_signed_in? %>
          <%= link_to( admins_homes_top_path, :style=>"text-decoration: none;", data: {"turbolinks" => false}) do %>
            <span class="rogo">ParkFun</span>
         <% end %>
        <% else %>
          <%= link_to(("/"), :style=>"text-decoration: none;", data: {"turbolinks" => false}) do %>
            <span class="rogo">ParkFun</span>
          <% end %>
        <% end %>
      </div>
      <nav id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right" style="font-size: 16px;">
          <% if user_signed_in? %><!-- 会員ログイン後 -->
            <li class="user">ようこそ、　<%= current_user.name %>　さん！</li>
            <li><%= link_to "マイページ", user_path(current_user.id), :style=>"color: white;" %></li>
            <li><%= link_to "アバウト", home_about_path, :style=>"color: white;" %></li>
            <li><%= link_to "公園検索", search_path, :style=>"color: white;" %></li>
            <li><%= link_to "投稿一覧", posts_path, :style=>"color: white;" %></li>
            <li><%= link_to "投稿する", new_post_path, :style=>"color: white;" %></li>
            <% if unchecked_notifications.any? %>
              <li><%= link_to notifications_path do %>
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true" style="color: red;">通知あり</span>
              </li>
              <% end %>
            <% else %>
              <li><%= link_to "通知なし", notifications_path, :style=>"color: white;" %></li>
            <% end %>
            <li><%= link_to "お問い合わせ", contacts_new_path, :style=>"color: white;" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, :style=>"color: white;" %></li>
          <% elsif admin_signed_in? %><!-- 管理者ログイン後 -->
            <li class="user">管理者ログイン中</li>
            <li><%= link_to "投稿一覧", admins_posts_path, :style=>"color: white;" %></li>
            <li><%= link_to "会員一覧", admins_users_path, :style=>"color: white;" %></li>
            <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, :style=>"color: white;" %></li>
          <% else %><!-- 非ログイン -->
            <li><%= link_to "アバウト", home_about_path, :style=>"color: white;" %></li>
            <li><%= link_to "新規登録", new_user_registration_path, :style=>"color: white;", data: {"turbolinks" => false} %></li>
            <li><%= link_to "ログイン", new_user_session_path, :style=>"color: white;" %></li>
            <li><%= link_to "管理者用ログイン", new_admin_session_path, :style=>"color: white;" %></li>
          <% end %>
        </ul>
      </nav>
    </nav>

    <%= yield %>
    <footer class="hoge_footer" style="padding: 20px;">
      <span style="color: white; margin-left: 550px;">2020 (C) YusakuIwata. All Rights Reserved.</span>
    </footer>
  </body>
</html>